version: '2'
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - decorder
    - dupl
    - dupword
    - errchkjson
    - errname
    - exhaustive
    - ginkgolinter
    - gocheckcompilerdirectives
    - goheader
    - gomoddirectives
    - gomodguard
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nilerr
    - nosprintfhostport
    - paralleltest
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint

  settings:
    revive:
      rules:
        - name: indent-error-flow
          disabled: true
    dupl:
      threshold: 200
    exhaustive:
      default-signifies-exhaustive: true
    misspell:
      locale: US
    rowserrcheck:
      packages: [github.com/jmoiron/sqlx]
    testpackage:
      skip-regexp: (export|internal)_test\.go
    whitespace:
      multi-if: false
      multi-func: false

  exclusions:
    generated: strict
    warn-unused: true
    paths:
      - src/external_libs
      - autogenerated_by_my_lib
      - '^_.*'
      - ".*\\.log$"
      - .gitlab-ci.yml
      - .golangci.lint.yml
    rules:
      - text: 'ineffectual assignment to `.*` (ineffassign)'
        linters: [ineffassign]
      - text: 'shadow: declaration of ".*" shadows declaration'
        linters: [govet]
      - text: '^exported [^ ]* .* should have comment'
        linters: [revive, stylecheck]
      - text: '^comment on'
        linters: [revive, stylecheck]
      - text: 'should be'
        linters: [revive]
      - path: mocks/.*\.go
        linters: [revive, stylecheck, dupl]
      - path: _test\.go
        linters: [revive, stylecheck, dupl]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
  fix: false

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  sort-order: [linter, file]
  show-stats: true

run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 1
  tests: false
  build-tags: [mytag]
  allow-parallel-runners: false
  allow-serial-runners: false
  concurrency: 4

severity:
  default: error
  rules:
    - linters: [dupl]
      severity: info
