version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - godox
    - err113
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint

  settings:
    revive:
      rules:
        - name: indent-error-flow
          disabled: true
    dupl:
      threshold: 200
    exhaustive:
      default-signifies-exhaustive: true
    gocognit:
      min-complexity: 35
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 10
    godox:
      keywords: [NOTE, OPTIMIZE, HACK]
    lll:
      line-length: 120
      tab-width: 4
    gosec:
      excludes: [G301, G304]
    misspell:
      locale: US
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    rowserrcheck:
      packages: [github.com/jmoiron/sqlx]
    testpackage:
      skip-regexp: (export|internal)_test\.go
    whitespace:
      multi-if: false
      multi-func: false

  exclusions:
    generated: strict
    warn-unused: true
    paths:
      - src/external_libs
      - autogenerated_by_my_lib
      - "^_.*"
      - ".*\\.log$"
      - .gitlab-ci.yml
      - .golangci.lint.yml
    rules:
      - text: "ineffectual assignment to `.*` (ineffassign)"
        linters: [ineffassign]
      - text: 'shadow: declaration of ".*" shadows declaration'
        linters: [govet]
      - text: "^exported [^ ]* .* should have comment"
        linters: [revive, stylecheck]
      - text: "^comment on"
        linters: [revive, stylecheck]
      - text: "should be"
        linters: [revive]
      - path: mocks/.*\.go
        linters: [revive, stylecheck, lll, dupl, gosec]
      - path: _test\.go
        linters: [revive, stylecheck, gocyclo, dupl, gosec, lll]
      - path: html_.*\.go
        linters: [lll]
      - path: model/.*\.go
        linters: [lll]
      - linters: [gosec]
        text: G402
      - linters: [gosec]
        text: G501
      - linters: [gosec]
        text: G404
      - linters: [gosec]
        text: G401
      - linters: [gosec]
        text: G505
      - linters: [staticcheck]
        text: "SA9003:"
      - linters: [lll]
        source: '^//go:generate '

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
  fix: false

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  sort-order: [linter, file]
  show-stats: true

run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 1
  tests: false
  build-tags: [mytag]
  allow-parallel-runners: false
  allow-serial-runners: false
  concurrency: 4

severity:
  default: error
  rules:
    - linters: [dupl]
      severity: info
