version: "2"
services:

  go-ramjet:
    image: ppcelery/go-ramjet:pateo
    restart: "on-failure"
    networks:
      - go-ramjet
    ports:
      - 24087:24087
    logging:
      driver: "fluentd"
      options:
        tag: ramjet.sit
        fluentd-address: hbase1.sit.ptcloud.t.home:24225
    volumes:
      - /data/fluentd/fluentd-conf/backups:/data/fluentd/fluentd-conf/backups
      - /opt/configs/go-ramjet/settings.yml:/etc/go-ramjet/settings/settings.yml
    entrypoint: ./go-ramjet --config=/etc/go-ramjet/settings --addr=0.0.0.0:24087 -t=heartbeat,es-monitor,fl-monitor,es-rollover,es-password

networks:
  go-ramjet:
    driver: bridge
