version: "2"
services:

  go-ramjet:
    image: ppcelery/go-ramjet:pateo
    restart: "on-failure"
    networks:
      - go-ramjet
    ports:
      - 24087:24087
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    environment:
      - TASKS=heartbeat,es-monitor,fl-monitor,es-rollover
    volumes:
      - /data/fluentd/fluentd-conf/backups:/data/fluentd/fluentd-conf/backups
      - /opt/configs/go-ramjet/settings.yml:/etc/go-ramjet/settings/settings.yml
    command: ./go-ramjet --config=/etc/go-ramjet/settings --addr=0.0.0.0:24087

networks:
  go-ramjet:
    driver: bridge
