version: "2"
services:

  go-ramjet:
    image: ppcelery/go-ramjet:pateo
    restart: "no"
    networks:
      - go-ramjet
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    environment:
      - TASKS=heartbeat,es-monitor,es-remove,fl-monitor,es-rollover
    volumes:
      - /data/fluentd/fluentd-conf/backups:/data/fluentd/fluentd-conf/backups
      - /etc/go-ramjet/settings/settings.yml:/etc/go-ramjet/settings/settings.yml

networks:
  go-ramjet:
    driver: bridge
