server:
  # (required) listen address
  addr: 0.0.0.0:24456
openai:
  # (required) openai api token
  token: "<YOUR_OPENAI_API_TOKEN>"

  # (required) openai api url
  api: "https://api.openai.com"

  # (optional) openai api proxy, default no proxy
  # proxy: "<YOUR_HTTP_PROXY>"

  # (optional) google analytics code, default no GA
  # ga: "<YOUR_GOOGLE_ANALYTICS_CODE>"

  # (optional) openai api chat max contexts, default to 7
  # max_sessions: 7

  # (optional) openai api chat max tokens, default to 500 (max 4050
  # max_tokens: 500

  # (optional) if frontend user use these tokens,
  # will rewrite to openai api token
  user_tokens:
  - token: "<DEFAULT_PROXY_TOKEN>"
    # (required) allowed models for this token
    allowed_models:
    - "gpt-3.5-turbo-0125"
    - "text-davinci-003"

  # (optional) rewrite third-parth frontend static libraries
  # static_libs:
  #   sse_js: "https://s3.laisky.com/static/sse/0.6.1/sse.js"
  #   bootstrap_js: "https://s3.laisky.com/static/twitter-bootstrap/5.2.3/js/bootstrap.bundle.min.js"
  #   bootstrap_css: "https://s3.laisky.com/static/twitter-bootstrap/5.2.3/css/bootstrap.min.css"
  #   bootstrap_icons: "https://s3.laisky.com/static/twitter-bootstrap/5.2.3/css/bootstrap.min.css"
  #   showdown_js: "https://s3.laisky.com/static/showdown/2.1.0/showdown.min.js"
  #   prism_js: "https://s3.laisky.com/static/prism/1.30.0/prism.js"
  #   prism_css: "https://s3.laisky.com/static/prism/1.30.0/prism.css"
