{
  "overrides": {
    "ajv@>=6.0.0 <6.14.0": "^6.14.0",
    "minimatch@>=3.0.0 <3.1.5": "^3.1.5",
    "flatted@>=3.0.0 <3.4.2": "^3.4.2",
    "picomatch@>=4.0.0 <4.0.4": "^4.0.4",
    "brace-expansion@>=1.0.0 <1.1.13": "^1.1.13",
    "uuid@>=11.0.0 <11.1.1": "^11.1.1",
    "postcss@>=8.0.0 <8.5.10": "^8.5.10",
    "katex@>=0.0.0 <0.19.0": "^0.19.0",
    "dompurify@>=3.0.0 <3.4.16": "^3.4.16"
  },
  "packages": [
    "."
  ],
  "strictPeerDependencies": true,
  "allowBuilds": {
    "esbuild": false,
    "katex": false,
    "unrs-resolver": false,
    "core-js": false,
    "@swc/core": false
  }
}
